server:
  port: 8001
eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:123456@peer2:8002/eureka/
    register-with-eureka: false
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456

